### ISSUE TITLE
npm install on mac m2 fails

### ISSUE THREAD

**Issue by DenisSergeevitch** [corbt/agent.exe#4]
By default it returns an error:
```
(base) ➜  agent.exe git:(main) npm install
npm error Invalid property "node"
```

To resolve it we need to update package.json:

"Invalid property 'node'" is caused by the presence of the "devEngines" field in package.json. This field is not supported in modern versions of npm, which is why I get error with npm 10.9.0.

Here is a quick fix for people who has the same error:

Open `package.json` and edit line `239`:

Before:

```
"devEngines": {
    "node": ">=14.x",
    "npm": ">=7.x"
}
```

After:

```
"engines": {
    "node": ">=14.x",
    "npm": ">=7.x"
}
```

Now `npm install` will work

**Comment by corbt** [comment]
Weird this does work on my m2 mac. I think `devEngines` is in fact a supported field? https://docs.npmjs.com/cli/v10/configuring-npm/package-json#devengines

**Comment by 1n1n1t3** [comment]
same happens on Windows. Had to manually change devEngines to engines

**Comment by brianjking** [comment]
I had to do this as well, M1 Mac with Sequoia.

**Comment by developerfred** [comment]
> By default it returns an error:
> 
> ```
> (base) ➜  agent.exe git:(main) npm install
> npm error Invalid property "node"
> ```
> 
> To resolve it we need to update package.json:
> 
> "Invalid property 'node'" is caused by the presence of the "devEngines" field in package.json. This field is not supported in modern versions of npm, which is why I get error with npm 10.9.0.
> 
> Here is a quick fix for people who has the same error:
> 
> Open `package.json` and edit line `239`:
> 
> Before:
> 
> ```
> "devEngines": {
>     "node": ">=14.x",
>     "npm": ">=7.x"
> }
> ```
> 
> After:
> 
> ```
> "engines": {
>     "node": ">=14.x",
>     "npm": ">=7.x"
> }
> ```
> 
> Now `npm install` will work

use nvm to control node version

**Comment by corbt** [comment]
Ok seems like this is a common issue, I just pushed an update that should fix!
